standalone: main.go
	go run main.go \
		-itype json \
		-ifile ../test/test.json \
		-doom 10 \
		-debug

runtime: main.go 
	go run main.go \
		-itype json \
		-ifile ../test/test.json \
		-doom 10 \
		-debug -runtime